# Generated by Django 5.2.7 on 2025-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
