# Generated by Django 5.2.7 on 2025-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_freelancer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
