# Generated by Django 5.2.7 on 2025-10-05 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('motivation', models.TextField()),
                ('amount_request', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('installments', models.IntegerField()),
                ('first_installment_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financings', to='freelancers.credittaker')),
                ('investors', models.ManyToManyField(blank=True, related_name='invested_financings', to='freelancers.investor')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
